### ISSUE TITLE
add mjd?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/ontology#2]
@ferrigno please describe what you needed here. @dsavchenko can contribute with his experience.

**Comment by volodymyrss** [comment]
For practical purposes here, @ferrigno can just add the terms from development version of the ontology https://raw.githubusercontent.com/oda-hub/dispatcher-app/master/tests/oda-ontology.ttl as I just added to the [guide](https://odahub.io/docs/guide-ontology/) (which you should read and consider a reference for action, and if unclear - complain)

**Comment by volodymyrss** [comment]
since the terms already exist (e.g. [http://odahub.io/ontology#EndTimeMJD](https://github.com/oda-hub/dispatcher-app/blob/master/tests/oda-ontology.ttl#EndTimeMJD)) I would consider this issue closed. Please reopen if unclear.

One thing for clarity is that we should track better revisions and origins of different ontology variants https://github.com/oda-hub/ontology/issues/3

**Comment by dsavchenko** [comment]
One thing to mention is that here ontology terms for parameters are used in outputs. This is completely OK, any quantity could be an output of the analysis, but we should think of expressing this use-case in the ontology.
